const categoryData = [
	{ img: "images/category1.jpg", name: "Dining" },
	{ img: "images/category2.jpg", name: "Living" },
	{ img: "images/category3.jpg", name: "Bedroom" },
];

const slidesArr = [
	"images/sliderImg1.jpg",
	"images/sliderImg2.jpg",
	"images/sliderImg3.jpg",
	"images/sliderImg4.jpg",
];

const galleryImages = [
	"images/galleryImg1.jpg",
	"images/galleryImg2.jpg",
	"images/galleryImg3.jpg",
	"images/galleryImg4.jpg",
	"images/galleryImg5.jpg",
	"images/galleryImg6.jpg",
	"images/galleryImg7.jpg",
	"images/galleryImg8.jpg",
	"images/galleryImg9.jpg",
];

const productsList = [
	{
		name: "Syltherine",
		category: "Stylish cafe chair",
		price: 3500,
		discountPercent: 30,
		isNew: true,
		isWishlisted: true,
		img: "images/product1.jpg",
	},
	{
		name: "Modern Leather Sofa",
		category: "Sofa",
		price: 800,
		discountPercent: 20,
		isNew: false,
		isWishlisted: false,
		img: "images/product2.jpg",
	},
	{
		name: "Wooden Coffee Table",
		category: "Table",
		price: 550,
		discountPercent: 15,
		isNew: true,
		isWishlisted: false,
		img: "images/product3.jpg",
	},
	{
		name: "Comfortable Recliner Chair",
		category: "Chair",
		price: 700,
		discountPercent: 25,
		isNew: false,
		isWishlisted: false,
		img: "images/product4.jpg",
	},
	{
		name: "Vintage Bookshelf",
		category: "Shelf",
		price: 650,
		discountPercent: 10,
		isNew: false,
		isWishlisted: true,
		img: "images/product5.jpg",
	},
	{
		name: "Elegant Dining Table",
		category: "Table",
		price: 900,
		discountPercent: 18,
		isNew: true,
		isWishlisted: false,
		img: "images/product6.jpg",
	},
	{
		name: "Contemporary Office Desk",
		category: "Desk",
		price: 800,
		discountPercent: 15,
		isNew: false,
		isWishlisted: false,
		img: "images/product7.jpg",
	},
	{
		name: "Cozy Lounge Chair",
		category: "Chair",
		price: 600,
		discountPercent: 12,
		isNew: true,
		isWishlisted: true,
		img: "images/product8.jpg",
	},
	{
		name: "Antique Side Table",
		category: "Table",
		price: 530,
		discountPercent: 8,
		isNew: false,
		isWishlisted: false,
		img: "images/product9.jpg",
	},
	{
		name: "Classic Wardrobe",
		category: "Wardrobe",
		price: 1000,
		discountPercent: 22,
		isNew: true,
		isWishlisted: true,
		img: "images/product10.jpg",
	},
	// Add 20 more products below...
	{
		name: "Rustic Bed Frame",
		category: "Bed",
		price: 700,
		discountPercent: 15,
		isNew: false,
		isWishlisted: false,
		img: "images/product11.jpg",
	},
	{
		name: "Chic Vanity Mirror",
		category: "Mirror",
		price: 600,
		discountPercent: 10,
		isNew: true,
		isWishlisted: true,
		img: "images/product12.jpg",
	},
	{
		name: "Leather Office Chair",
		category: "Chair",
		price: 800,
		discountPercent: 20,
		isNew: false,
		isWishlisted: false,
		img: "images/product13.jpg",
	},
	{
		name: "Glass Top End Table",
		category: "Table",
		price: 700,
		discountPercent: 5,
		isNew: true,
		isWishlisted: false,
		img: "images/product14.jpg",
	},
	{
		name: "Industrial Bar Stool",
		category: "Stool",
		price: 600,
		discountPercent: 15,
		isNew: false,
		isWishlisted: false,
		img: "images/product15.jpg",
	},
	{
		name: "Corner Display Shelf",
		category: "Shelf",
		price: 700,
		discountPercent: 12,
		isNew: true,
		isWishlisted: false,
		img: "images/product16.jpg",
	},
	{
		name: "Folding Patio Chair",
		category: "Outdoor",
		price: 600,
		discountPercent: 8,
		isNew: false,
		isWishlisted: false,
		img: "images/product17.jpg",
	},
	{
		name: "Mirrored Dresser",
		category: "Dresser",
		price: 800,
		discountPercent: 25,
		isNew: true,
		isWishlisted: false,
		img: "images/product18.jpg",
	},
	{
		name: "Mid-Century Modern Desk",
		category: "Desk",
		price: 700,
		discountPercent: 15,
		isNew: false,
		isWishlisted: false,
		img: "images/product19.jpg",
	},
	{
		name: "Velvet Accent Chair",
		category: "Chair",
		price: 750,
		discountPercent: 18,
		isNew: true,
		isWishlisted: false,
		img: "images/product20.jpg",
	},
	{
		name: "Sleek Entertainment Center",
		category: "Entertainment",
		price: 900,
		discountPercent: 20,
		isNew: false,
		isWishlisted: false,
		img: "images/product21.jpg",
	},
	{
		name: "Rattan Patio Furniture Set",
		category: "Outdoor",
		price: 1000,
		discountPercent: 10,
		isNew: true,
		isWishlisted: true,
		img: "images/product22.jpg",
	},
	{
		name: "Tufted Ottoman",
		category: "Ottoman",
		price: 700,
		discountPercent: 15,
		isNew: false,
		isWishlisted: false,
		img: "images/product23.jpg",
	},
	{
		name: "Classic Four-Poster Bed",
		category: "Bed",
		price: 800,
		discountPercent: 22,
		isNew: true,
		isWishlisted: false,
		img: "images/product24.jpg",
	},
	{
		name: "Floating Wall Shelves",
		category: "Shelf",
		price: 600,
		discountPercent: 8,
		isNew: false,
		isWishlisted: false,
		img: "images/product25.jpg",
	},
	{
		name: "Adjustable Standing Desk",
		category: "Desk",
		price: 900,
		discountPercent: 15,
		isNew: true,
		isWishlisted: false,
		img: "images/product26.jpg",
	},
	{
		name: "Plush Bean Bag Chair",
		category: "Chair",
		price: 700,
		discountPercent: 10,
		isNew: false,
		isWishlisted: false,
		img: "images/product27.jpg",
	},
	{
		name: "Farmhouse Dining Table",
		category: "Table",
		price: 700,
		discountPercent: 18,
		isNew: true,
		isWishlisted: false,
		img: "images/product28.jpg",
	},
	{
		name: "Swivel Bar Stool",
		category: "Stool",
		price: 600,
		discountPercent: 12,
		isNew: false,
		isWishlisted: false,
		img: "images/product29.jpg",
	},
	{
		name: "Rolling File Cabinet",
		category: "Storage",
		price: 700,
		discountPercent: 15,
		isNew: true,
		isWishlisted: false,
		img: "images/product30.jpg",
	},
];

export { categoryData, slidesArr, galleryImages, productsList };
