const productsList = [
	{
		id: 1,
		name: "Aurora",
		category: "Stylish cafe chair",
		price: 3500,
		discountPercent: 30,
		featured: true,
		isNew: true,
		isWishlisted: true,
		img: "images/product1.jpg",
	},
	{
		id: 2,
		name: "Zenith",
		category: "Sofa",
		price: 800,
		discountPercent: 20,
		featured: true,
		isNew: false,
		isWishlisted: false,
		img: "images/product2.jpg",
	},
	{
		id: 3,
		name: "Cascade",
		category: "Table",
		price: 550,
		discountPercent: 15,
		featured: true,
		isNew: true,
		isWishlisted: false,
		img: "images/product3.jpg",
	},
	{
		id: 4,
		name: "Serenity",
		category: "Chair",
		price: 700,
		discountPercent: 25,
		featured: true,
		isNew: false,
		isWishlisted: false,
		img: "images/product4.jpg",
	},
	{
		id: 5,
		name: "Harmony",
		category: "Shelf",
		price: 650,
		discountPercent: 10,
		featured: true,
		isNew: false,
		isWishlisted: true,
		img: "images/product5.jpg",
	},
	{
		id: 6,
		name: "Elysian",
		category: "Table",
		price: 900,
		discountPercent: 18,
		featured: true,
		isNew: true,
		isWishlisted: false,
		img: "images/product6.jpg",
	},
	{
		id: 7,
		name: "Tranquil",
		category: "Desk",
		price: 800,
		discountPercent: 15,
		featured: true,
		isNew: false,
		isWishlisted: false,
		img: "images/product7.jpg",
	},
	{
		id: 8,
		name: "Vivid",
		category: "Chair",
		price: 600,
		discountPercent: 12,
		featured: true,
		isNew: true,
		isWishlisted: true,
		img: "images/product8.jpg",
	},
	{
		id: 9,
		name: "Aspen",
		category: "Table",
		price: 530,
		discountPercent: 8,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product9.jpg",
	},
	{
		id: 10,
		name: "Luminary",
		category: "Wardrobe",
		price: 1000,
		discountPercent: 22,
		featured: false,
		isNew: true,
		isWishlisted: true,
		img: "images/product10.jpg",
	},
	{
		id: 11,
		name: "Sundown",
		category: "Bed",
		price: 700,
		discountPercent: 15,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product11.jpg",
	},
	{
		id: 12,
		name: "Echo",
		category: "Mirror",
		price: 600,
		discountPercent: 10,
		featured: false,
		isNew: true,
		isWishlisted: true,
		img: "images/product12.jpg",
	},
	{
		id: 13,
		name: "Oasis",
		category: "Chair",
		price: 800,
		discountPercent: 20,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product13.jpg",
	},
	{
		id: 14,
		name: "Horizon",
		category: "Table",
		price: 700,
		discountPercent: 5,
		featured: false,
		isNew: true,
		isWishlisted: false,
		img: "images/product14.jpg",
	},
	{
		id: 15,
		name: "Zen",
		category: "Stool",
		price: 600,
		discountPercent: 15,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product15.jpg",
	},
	{
		id: 16,
		name: "Crest",
		category: "Shelf",
		price: 700,
		discountPercent: 12,
		featured: false,
		isNew: true,
		isWishlisted: false,
		img: "images/product16.jpg",
	},
	{
		id: 17,
		name: "Breeze",
		category: "Outdoor",
		price: 600,
		discountPercent: 8,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product17.jpg",
	},
	{
		id: 18,
		name: "Astral",
		category: "Dresser",
		price: 800,
		discountPercent: 25,
		featured: false,
		isNew: true,
		isWishlisted: false,
		img: "images/product18.jpg",
	},
	{
		id: 19,
		name: "Verve",
		category: "Desk",
		price: 700,
		discountPercent: 15,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product19.jpg",
	},
	{
		id: 20,
		name: "Lux",
		category: "Chair",
		price: 750,
		discountPercent: 18,
		featured: false,
		isNew: true,
		isWishlisted: false,
		img: "images/product20.jpg",
	},
	{
		id: 21,
		name: "Nova",
		category: "Entertainment",
		price: 900,
		discountPercent: 20,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product21.jpg",
	},
	{
		id: 22,
		name: "Eden",
		category: "Outdoor",
		price: 1000,
		discountPercent: 10,
		featured: false,
		isNew: true,
		isWishlisted: true,
		img: "images/product22.jpg",
	},
	{
		id: 23,
		name: "Plush",
		category: "Ottoman",
		price: 700,
		discountPercent: 15,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product23.jpg",
	},
	{
		id: 24,
		name: "Majestic",
		category: "Bed",
		price: 800,
		discountPercent: 22,
		featured: false,
		isNew: true,
		isWishlisted: false,
		img: "images/product24.jpg",
	},
	{
		id: 25,
		name: "Vista",
		category: "Shelf",
		price: 600,
		discountPercent: 8,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product25.jpg",
	},
	{
		id: 26,
		name: "Zenith",
		category: "Desk",
		price: 900,
		discountPercent: 15,
		featured: false,
		isNew: true,
		isWishlisted: false,
		img: "images/product26.jpg",
	},
	{
		id: 27,
		name: "Cozy",
		category: "Chair",
		price: 700,
		discountPercent: 10,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product27.jpg",
	},
	{
		id: 28,
		name: "Meadow",
		category: "Table",
		price: 700,
		discountPercent: 18,
		featured: false,
		isNew: true,
		isWishlisted: false,
		img: "images/product28.jpg",
	},
	{
		id: 29,
		name: "Sway",
		category: "Stool",
		price: 600,
		discountPercent: 12,
		featured: false,
		isNew: false,
		isWishlisted: false,
		img: "images/product29.jpg",
	},
	{
		id: 30,
		name: "Cabinet",
		category: "Storage",
		price: 700,
		discountPercent: 15,
		featured: false,
		isNew: true,
		isWishlisted: false,
		img: "images/product30.jpg",
	},
];

// Add more products with unique id values as needed

export default productsList;
